"""Fix missing fields in MagDB supplements.

Revision ID: 00191d8fc360
Revises: c69659a392d3
Create Date: 2023-11-25 10:43:35.261755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00191d8fc360'
down_revision = 'c69659a392d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'issuestatus', ['have', 'dont_have', 'problems'], ['have', 'dont_have', 'problems', 'existence_unconfirmed'])
    op.add_column('magazine_supplement', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('magazine_supplement', sa.Column('status', sa.Enum('have', 'dont_have', 'problems', 'existence_unconfirmed', name='issuestatus'), nullable=True))
    op.add_column('magazine_supplement', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'magazine_supplement', ['id'])
    op.add_column('magazine_supplement_version', sa.Column('magazine_issue_version_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'magazine_supplement_version', ['id'])
    op.create_foreign_key(None, 'magazine_supplement_version', 'magazine_issue_versions', ['magazine_issue_version_id'], ['id'])
    op.create_unique_constraint(None, 'magazine_supplement_version_files', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magazine_supplement_version_files', type_='unique')
    op.drop_constraint(None, 'magazine_supplement_version', type_='foreignkey')
    op.drop_constraint(None, 'magazine_supplement_version', type_='unique')
    op.drop_column('magazine_supplement_version', 'magazine_issue_version_id')
    op.drop_constraint(None, 'magazine_supplement', type_='unique')
    op.drop_column('magazine_supplement', 'confirmed')
    op.drop_column('magazine_supplement', 'status')
    op.drop_column('magazine_supplement', 'note')
    # ### end Alembic commands ###
