"""Add MagDB tables.

Revision ID: 00955b32a31b
Revises: 3dd084df4064
Create Date: 2022-10-22 04:08:36.519045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00955b32a31b'
down_revision = '3dd084df4064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formats',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binding_type', sa.Enum('glued', 'stapled', 'none', 'sewn', 'not_applicable', name='bindingtype'), nullable=True),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('issuers',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('magazines',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('magazine_issues',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sa.String(length=64), nullable=True),
    sa.Column('issue_title', sa.String(length=127), nullable=True),
    sa.Column('current_magazine_name', sa.String(length=127), nullable=True),
    sa.Column('is_special_issue', sa.Boolean(), nullable=True),
    sa.Column('periodicity', sa.Enum('weekly', 'biweekly', 'monthly', 'bimonthly', 'quarterly', 'annually', 'non_periodical', name='periodicity'), nullable=True),
    sa.Column('published_day', sa.Integer(), nullable=True),
    sa.Column('published_month', sa.Integer(), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('circulation', sa.Integer(), nullable=True),
    sa.Column('chief_editor_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.Column('magazine_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chief_editor_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['issuers.id'], ),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('magazine_issue_versions',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magazine_issue_id', sa.Integer(), nullable=False),
    sa.Column('name_suffix', sa.String(length=127), nullable=True),
    sa.Column('form', sa.Enum('electronic', 'paper', 'CD', 'DVD', 'diskette', name='magazineform'), nullable=True),
    sa.Column('format_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('isbn', sa.String(length=25), nullable=True),
    sa.Column('barcode', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('have', 'dont_have', 'problems', name='issuestatus'), nullable=True),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], ),
    sa.ForeignKeyConstraint(['magazine_issue_id'], ['magazine_issues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('magazine_issue_version_prices',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_version_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.Enum('CZK', 'EUR', 'CSK', 'SK', 'PLN', 'GBP', name='currency'), nullable=True),
    sa.ForeignKeyConstraint(['issue_version_id'], ['magazine_issue_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magazine_issue_version_prices')
    op.drop_table('magazine_issue_versions')
    op.drop_table('magazine_issues')
    op.drop_table('magazines')
    op.drop_table('issuers')
    op.drop_table('formats')
    # ### end Alembic commands ###
