"""Add statement aggregate

Revision ID: 086cd4bf22b6
Revises: 59333a5074ef
Create Date: 2026-05-17 21:18:00.330041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086cd4bf22b6'
down_revision = '59333a5074ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_statements',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_event_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agg_statements_subject_id'), 'agg_statements', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agg_statements_subject_id'), table_name='agg_statements')
    op.drop_table('agg_statements')
    # ### end Alembic commands ###
