"""Add new asset categories

Revision ID: 0923c8b71af8
Revises: 990b9a3166b8
Create Date: 2022-11-05 18:39:42.023929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0923c8b71af8'
down_revision = '990b9a3166b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for new_category in ['packaging', 'location']:
        op.execute("COMMIT")
        op.execute(f"ALTER TYPE assetcategory ADD VALUE '{new_category}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
