"""Asset condition_new column

Revision ID: 09e7b390eb7f
Revises: a1aa32383d75
Create Date: 2022-09-20 19:41:09.941490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '09e7b390eb7f'
down_revision = 'a1aa32383d75'
branch_labels = None
depends_on = None

AssetCategoryPostgresEnum = postgresql.ENUM('unknown', 'mint', 'scuffed', 'damaged', 'garbage', name='assetcondition')


def upgrade():
    bind = op.get_bind()
    AssetCategoryPostgresEnum.create(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('condition_new', sa.Enum('unknown', 'mint', 'scuffed', 'damaged', 'garbage', name='assetcondition'), nullable=False, server_default='unknown'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'condition_new')
    # ### end Alembic commands ###
