"""Make push key related columns in EventSession optional

Revision ID: 0a73573cde8f
Revises: 1b241a692fb5
Create Date: 2025-11-29 22:07:17.164938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a73573cde8f'
down_revision = '1b241a692fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_sessions', 'authorized_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('event_sessions', 'authorized_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_sessions', 'authorized_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event_sessions', 'authorized_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
