"""Add note to issue version.

Revision ID: 0b01e7f314d8
Revises: 3bf0784019fd
Create Date: 2023-01-28 12:01:56.113381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b01e7f314d8'
down_revision = '3bf0784019fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'formats', ['id'])
    op.create_unique_constraint(None, 'issuers', ['id'])
    op.create_unique_constraint(None, 'magazine_issue_files', ['id'])
    op.create_unique_constraint(None, 'magazine_issue_version_prices', ['id'])
    op.add_column('magazine_issue_versions', sa.Column('note', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'magazine_issue_versions', ['id'])
    op.create_unique_constraint(None, 'magazine_issues', ['id'])
    op.create_unique_constraint(None, 'magazines', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magazines', type_='unique')
    op.drop_constraint(None, 'magazine_issues', type_='unique')
    op.drop_constraint(None, 'magazine_issue_versions', type_='unique')
    op.drop_column('magazine_issue_versions', 'note')
    op.drop_constraint(None, 'magazine_issue_version_prices', type_='unique')
    op.drop_constraint(None, 'magazine_issue_files', type_='unique')
    op.drop_constraint(None, 'issuers', type_='unique')
    op.drop_constraint(None, 'formats', type_='unique')
    # ### end Alembic commands ###
