"""Remove unique key on MagazineSupplement.

Revision ID: 0e3519f2f8dc
Revises: 00191d8fc360
Create Date: 2023-11-25 13:48:49.718746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3519f2f8dc'
down_revision = '00191d8fc360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('magazine_supplement_title_key', 'magazine_supplement', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('magazine_supplement_title_key', 'magazine_supplement', ['title'])
    # ### end Alembic commands ###
