"""Add event store tables

Revision ID: 10c4d1c36bb3
Revises: e16129c911ec
Create Date: 2025-11-15 20:18:38.486958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c4d1c36bb3'
down_revision = 'e16129c911ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_push_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(), nullable=True),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.Column('authorized_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('event_push_key_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['event_push_key_id'], ['event_push_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('event_push_keys')
    # ### end Alembic commands ###
