"""fix

Revision ID: 195f4992e16e
Revises: 27d89e13e01c
Create Date: 2024-08-15 19:00:01.494084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195f4992e16e'
down_revision = '27d89e13e01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('hhprint', name='labelprintermethod'), nullable=False),
    sa.Column('printer', sa.String(), nullable=True),
    sa.Column('backend', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('users_label_printer_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'label_printers', ['label_printer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_label_printer_id_fkey', 'users', 'organizations', ['label_printer_id'], ['id'])
    op.drop_table('label_printers')
    # ### end Alembic commands ###
