"""add EventSession.internal

Revision ID: 1b241a692fb5
Revises: 94cd14d4353d
Create Date: 2025-11-29 21:52:28.441996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b241a692fb5'
down_revision = '94cd14d4353d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('internal', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('event_sessions', 'push_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_sessions', 'push_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('event_sessions', 'internal')
    # ### end Alembic commands ###
