"""Asset: Add product_codes

Revision ID: 1c630c618c9a
Revises: eb86981e00db
Create Date: 2022-04-11 21:11:11.060959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c630c618c9a'
down_revision = 'eb86981e00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('product_codes', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('assets', 'num_photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('num_photos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'product_codes')
    # ### end Alembic commands ###
