"""File storage to enum

Revision ID: 20d143552684
Revises: 421e5534b7b3
Create Date: 2023-02-05 15:48:24.104707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '20d143552684'
down_revision = '421e5534b7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'storage')
    filestore = postgresql.ENUM('local', 'local_nas', name='filestore')
    filestore.create(op.get_bind())
    op.add_column(
        'files', sa.Column('storage', filestore, server_default='local', nullable=False)
    )
    op.alter_column('files', 'storage',
               server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # Broken
    # ### end Alembic commands ###
