"""Add history field.

Revision ID: 253881199c98
Revises: 9f817789cd74
Create Date: 2023-06-07 10:09:13.260361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253881199c98'
down_revision = '9f817789cd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formats', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('issuers', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('magazine_issue_files', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('magazine_issue_version_prices', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('magazine_issue_versions', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('magazine_issues', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('magazines', sa.Column('history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'history')
    op.drop_column('magazine_issues', 'history')
    op.drop_column('magazine_issue_versions', 'history')
    op.drop_column('magazine_issue_version_prices', 'history')
    op.drop_column('magazine_issue_files', 'history')
    op.drop_column('issuers', 'history')
    op.drop_column('formats', 'history')
    # ### end Alembic commands ###
