"""Transaction finalized bool

Revision ID: 2662f6133944
Revises: 20d143552684
Create Date: 2023-02-07 19:31:27.594922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2662f6133944'
down_revision = '20d143552684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('finalized', sa.Boolean(), nullable=True, default=True, server_default="true"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'finalized')
    # ### end Alembic commands ###
