"""Add column to AssetTag

Revision ID: 2c6088a1ae40
Revises: 80b134bde2f5
Create Date: 2023-12-19 18:26:25.890008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6088a1ae40'
down_revision = '80b134bde2f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tags', sa.Column('is_collection', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tags', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'order')
    op.drop_column('tags', 'is_collection')
    op.drop_column('tags', 'is_featured')
    # ### end Alembic commands ###
