"""Add user to session table

Revision ID: 35012356b25e
Revises: bbbc6f6693ae
Create Date: 2025-11-30 13:10:58.621725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35012356b25e'
down_revision = 'bbbc6f6693ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_sessions', 'users', ['user_id'], ['id'])
    
    # Copy authorized_by_user_id from push_keys to event_sessions.user_id
    op.execute('''
        UPDATE event_sessions
        SET user_id = push_keys.authorized_by_user_id
        FROM push_keys
        WHERE event_sessions.push_key_id = push_keys.id
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_sessions', type_='foreignkey')
    op.drop_column('event_sessions', 'user_id')
    # ### end Alembic commands ###
