"""Add batch number to File

Revision ID: 3598f0d2ca40
Revises: 8d2434c1a72a
Create Date: 2021-11-21 16:22:04.311847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3598f0d2ca40'
down_revision = '8d2434c1a72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('batch_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'batch_number')
    # ### end Alembic commands ###
