"""Add floppy disk capture reassignment fields

Revision ID: 4259ca42a30d
Revises: f67992ffdd05
Create Date: 2025-12-14 22:10:22.223120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4259ca42a30d'
down_revision = 'f67992ffdd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = postgresql.ENUM('FILENAME', 'REASSIGNMENT', name='assetidsource')
    enum.create(op.get_bind())
    
    op.add_column('agg_floppy_disk_captures', sa.Column('asset_id_source', enum, nullable=True))
    op.add_column('agg_floppy_disk_captures', sa.Column('asset_id_from_filename', sa.Integer(), nullable=True))
    op.add_column('agg_floppy_disk_captures', sa.Column('filename_incorrect', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agg_floppy_disk_captures', 'filename_incorrect')
    op.drop_column('agg_floppy_disk_captures', 'asset_id_from_filename')
    op.drop_column('agg_floppy_disk_captures', 'asset_id_source')
    # ### end Alembic commands ###
