"""Rename EventPushKey to EventSession

Revision ID: 439778c97582
Revises: 4c08bd74399b
Create Date: 2025-11-29 21:31:07.707890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '439778c97582'
down_revision = '4c08bd74399b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('event_push_keys', 'event_sessions')
    op.execute('ALTER SEQUENCE  event_push_keys_id_seq RENAME TO event_sessions_id_seq')
    op.execute('ALTER INDEX ix_event_push_keys_key RENAME TO ix_event_sessions_key')


    op.drop_constraint(op.f('events_event_push_key_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'event_sessions', ['event_push_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Downgrade not supported for this migration.")
    # ### end Alembic commands ###
