"""Add file aggregate table

Revision ID: 494b12e5cb4c
Revises: e2b14e1a005e
Create Date: 2025-12-17 19:04:11.593257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494b12e5cb4c'
down_revision = 'e2b14e1a005e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_files',
    sa.Column('hash_md5', sa.LargeBinary(), nullable=True),
    sa.Column('hash_sha256', sa.LargeBinary(), nullable=True),
    sa.Column('hash_blake3', sa.LargeBinary(), nullable=True),
    sa.Column('file_conversion_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_event_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agg_files')
    # ### end Alembic commands ###
