"""Fix files in MagDB.

Revision ID: 4bbb9b42edc7
Revises: a97d1f1210d8
Create Date: 2023-01-08 22:49:28.918099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbb9b42edc7'
down_revision = 'a97d1f1210d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazine_issue_files',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magazine_issue_version_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('logo', 'scan', 'cover_page', 'index_page', name='magdbfiletype'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['magazine_issue_version_id'], ['magazine_issue_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_constraint('files_magazine_issue_id_fkey', 'files', type_='foreignkey')
    op.drop_constraint('files_magazine_issue_version_id_fkey', 'files', type_='foreignkey')
    op.drop_column('files', 'magazine_issue_id')
    op.drop_column('files', 'magazine_issue_version_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('magazine_issue_version_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('magazine_issue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('files_magazine_issue_version_id_fkey', 'files', 'magazine_issue_versions', ['magazine_issue_version_id'], ['id'])
    op.create_foreign_key('files_magazine_issue_id_fkey', 'files', 'magazine_issues', ['magazine_issue_id'], ['id'])
    op.drop_table('magazine_issue_files')
    # ### end Alembic commands ###
