"""Change event ID into uuid

Revision ID: 4c08bd74399b
Revises: f41023979088
Create Date: 2025-11-19 20:40:02.185381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c08bd74399b'
down_revision = 'f41023979088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_push_keys_key'), 'event_push_keys', ['key'], unique=False)
    op.drop_column('events', 'id')
    op.add_column('events', sa.Column('id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_event_push_keys_key'), table_name='event_push_keys')
    # ### end Alembic commands ###
