"""Asset: add description

Revision ID: 52e6ee4f9e72
Revises: 67c7642b8ef5
Create Date: 2025-01-06 22:21:59.571846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52e6ee4f9e72'
down_revision = '67c7642b8ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'description')
    # ### end Alembic commands ###
