"""Add agg_files.last_known_aggregate

Revision ID: 537c1de085d1
Revises: 494b12e5cb4c
Create Date: 2025-12-17 19:15:09.652274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537c1de085d1'
down_revision = '494b12e5cb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agg_files', sa.Column('last_known_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agg_files', 'last_known_filename')
    # ### end Alembic commands ###
