"""Add format column to Log table

Revision ID: 54a5494e2f6a
Revises: c49e9ca7103f
Create Date: 2023-10-14 15:40:26.555210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a5494e2f6a'
down_revision = 'c49e9ca7103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('object_json_new_format', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'object_json_new_format')
    # ### end Alembic commands ###
