"""Magazine.url_issue_scan_template

Revision ID: 59333a5074ef
Revises: e4fda14b7cd7
Create Date: 2026-03-05 17:33:27.709943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59333a5074ef'
down_revision = 'e4fda14b7cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('url_issue_scan_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'url_issue_scan_template')
    # ### end Alembic commands ###
