"""Add computer relationships to main tables

Revision ID: 59d249ebf873
Revises: 3822d04489a0
Create Date: 2021-10-18 22:09:17.874127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d249ebf873'
down_revision = '3822d04489a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('hardware_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'hardware_type', ['hardware_type_id'], ['id'])
    op.add_column('files', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('benchmark_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'transactions', ['transaction_id'], ['id'])
    op.create_foreign_key(None, 'files', 'benchmark', ['benchmark_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'benchmark_id')
    op.drop_column('files', 'transaction_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'hardware_type_id')
    # ### end Alembic commands ###
