"""TransactionType.trade

Revision ID: 5b3e7a835057
Revises: 89a1b1be05ee
Create Date: 2026-09-10 17:58:19.347195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3e7a835057'
down_revision = '89a1b1be05ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'filestore', ['local', 'local_nas'], ['coruscant', 'local', 'local_nas'], [('files', 'storage')], False)
    op.sync_enum_values('public', 'transactiontype', ['acquisition', 'borrow', 'creation', 'disposal', 'donation_in', 'donation_out', 'lend', 'loss', 'purchase', 'return_in', 'return_out', 'sale', 'unknown'], ['acquisition', 'borrow', 'creation', 'disposal', 'donation_in', 'donation_out', 'lend', 'loss', 'purchase', 'return_in', 'return_out', 'sale', 'trade_in', 'trade_out', 'unknown'], [('transactions', 'transaction_type')], False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'transactiontype', ['acquisition', 'borrow', 'creation', 'disposal', 'donation_in', 'donation_out', 'lend', 'loss', 'purchase', 'return_in', 'return_out', 'sale', 'trade_in', 'trade_out', 'unknown'], ['acquisition', 'borrow', 'creation', 'disposal', 'donation_in', 'donation_out', 'lend', 'loss', 'purchase', 'return_in', 'return_out', 'sale', 'unknown'], [('transactions', 'transaction_type')], True)
    op.sync_enum_values('public', 'filestore', ['coruscant', 'local', 'local_nas'], ['local', 'local_nas'], [('files', 'storage')], True)
    # ### end Alembic commands ###
