"""Add asset companies n-to-n table

Revision ID: 5f970ea791b9
Revises: 476d56aba399
Create Date: 2022-10-23 20:14:08.834250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f970ea791b9'
down_revision = '476d56aba399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_company',
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], )
    )
    op.drop_table('product_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name='product_codes_asset_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_codes_pkey')
    )
    op.drop_table('asset_company')
    # ### end Alembic commands ###
