"""Bookmarks table

Revision ID: 6dc4b06bff6c
Revises: 0c6e55fa2086
Create Date: 2022-11-15 20:17:35.482086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc4b06bff6c'
down_revision = '0c6e55fa2086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=True),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarks')
    # ### end Alembic commands ###
