"""Magazine.url_oldgames_sk

Revision ID: 6fa15bc35f26
Revises: 70e20b316ae7
Create Date: 2026-02-07 13:03:27.505641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa15bc35f26'
down_revision = '70e20b316ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('url_oldgames_sk', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'url_oldgames_sk')
    # ### end Alembic commands ###
