"""Magazine.description_en, blurb_cs, blurb_en

Revision ID: 70e20b316ae7
Revises: b943b482152b
Create Date: 2026-02-07 12:39:13.777062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e20b316ae7'
down_revision = 'b943b482152b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('description_en', sa.Text(), nullable=True))
    op.add_column('magazines', sa.Column('blurb_cs', sa.Text(), nullable=True))
    op.add_column('magazines', sa.Column('blurb_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'blurb_en')
    op.drop_column('magazines', 'blurb_cs')
    op.drop_column('magazines', 'description_en')
    # ### end Alembic commands ###
