"""Asset: created_at and made_public_at

Revision ID: 71858021f889
Revises: 2c6088a1ae40
Create Date: 2024-01-29 17:48:01.095027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71858021f889'
down_revision = '2c6088a1ae40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('made_public_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'made_public_at')
    op.drop_column('assets', 'created_at')
    # ### end Alembic commands ###
