"""Add disassociation to FloppyDiskCapture agg

Revision ID: 7c2194c5fb95
Revises: 8b02a5d56bb0
Create Date: 2025-12-01 20:42:05.173303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2194c5fb95'
down_revision = '8b02a5d56bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agg_floppy_disk_captures', sa.Column('disassociated', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agg_floppy_disk_captures', 'disassociated')
    # ### end Alembic commands ###
