"""MagazineIssue.scan_url

Revision ID: 89a1b1be05ee
Revises: a822823872de
Create Date: 2026-09-03 22:31:49.047507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a1b1be05ee'
down_revision = 'a822823872de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazine_issues', sa.Column('scan_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazine_issues', 'scan_url')
    # ### end Alembic commands ###
