"""create FloppyDiskCapture

Revision ID: 8b02a5d56bb0
Revises: e2082a9824a2
Create Date: 2025-12-01 19:06:02.200864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b02a5d56bb0'
down_revision = 'e2082a9824a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agg_floppy_disk_captures')
    op.create_table('agg_floppy_disk_captures',
    sa.Column('latest_pyhxcfe_run_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('dumped_at', sa.DateTime(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('directory_name', sa.String(), nullable=True),
    sa.Column('drive_name', sa.String(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('formats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('number_of_tracks', sa.Integer(), nullable=True),
    sa.Column('number_of_sides', sa.Integer(), nullable=True),
    sa.Column('has_errors', sa.Boolean(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('parsing_errors', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_event_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Commit the table creation so it's visible to the app context
    op.get_bind().commit()

    # Rebuild FloppyDiskCapture aggregates from events
    from rhinventory.app import create_app
    from rhinventory.models.aggregates.floppy_disk_capture import FloppyDiskCapture
    from rhinventory.event_store.event_store import EventStore

    app = create_app()
    with app.app_context():
        event_store = EventStore()
        event_store.rebuild_aggregates(aggregate_class=FloppyDiskCapture)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agg_floppy_disk_captures')
    # ### end Alembic commands ###
