"""Grow Party table and add Transaction columns

Revision ID: 8d2434c1a72a
Revises: aa274b1d029d
Create Date: 2021-11-09 21:58:29.540961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2434c1a72a'
down_revision = 'aa274b1d029d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parties', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('parties', sa.Column('is_member', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('our_party_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('counterparty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'parties', ['counterparty_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'parties', ['our_party_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'counterparty_id')
    op.drop_column('transactions', 'our_party_id')
    op.drop_column('parties', 'is_member')
    op.drop_column('parties', 'legal_name')
    # ### end Alembic commands ###
