"""Rename DBEvent.push_key_id to event_session_id

Revision ID: 94cd14d4353d
Revises: e8e187bdb507
Create Date: 2025-11-29 21:49:36.872984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cd14d4353d'
down_revision = 'e8e187bdb507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_push_key_id', new_column_name='event_session_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Downgrade not supported for this migration.")
    # ### end Alembic commands ###
