"""Add files to MagDB entities.

Revision ID: 9b8aa0e04d0a
Revises: 00955b32a31b
Create Date: 2022-10-22 11:31:25.230226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8aa0e04d0a'
down_revision = '00955b32a31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('magazine_issue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'magazine_issues', ['magazine_issue_id'], ['id'])
    op.create_unique_constraint(None, 'formats', ['id'])
    op.create_unique_constraint(None, 'issuers', ['id'])
    op.create_unique_constraint(None, 'magazine_issue_version_prices', ['id'])
    op.create_unique_constraint(None, 'magazine_issue_versions', ['id'])
    op.create_unique_constraint(None, 'magazine_issues', ['id'])
    op.create_unique_constraint(None, 'magazines', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magazines', type_='unique')
    op.drop_constraint(None, 'magazine_issues', type_='unique')
    op.drop_constraint(None, 'magazine_issue_versions', type_='unique')
    op.drop_constraint(None, 'magazine_issue_version_prices', type_='unique')
    op.drop_constraint(None, 'issuers', type_='unique')
    op.drop_constraint(None, 'formats', type_='unique')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'magazine_issue_id')
    # ### end Alembic commands ###
