"""add_deleted_at_to_statement_aggregate

Revision ID: 9fcc68592c0d
Revises: 086cd4bf22b6
Create Date: 2026-05-18 21:18:06.994748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcc68592c0d'
down_revision = '086cd4bf22b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agg_statements', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agg_statements', 'property_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('agg_statements', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('agg_statements', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agg_statements', 'deleted_at')
    op.alter_column('agg_statements', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('agg_statements', 'property_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('agg_statements', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
