"""Add unique constraints to asset n-to-n tables

Revision ID: a822823872de
Revises: 9fcc68592c0d
Create Date: 2026-07-16 15:58:35.673298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a822823872de'
down_revision = '9fcc68592c0d'
branch_labels = None
depends_on = None


def upgrade():
    # Remove existing duplicate rows first; adding a unique constraint fails
    # if duplicates exist. These tables have no primary key, so use ctid.
    for table, other_column in [
        ('asset_assettag', 'assettag_id'),
        ('asset_company', 'company_id'),
        ('asset_platform', 'platform_id'),
    ]:
        op.execute(
            f"DELETE FROM {table} a USING {table} b "
            f"WHERE a.ctid < b.ctid "
            f"AND a.asset_id = b.asset_id AND a.{other_column} = b.{other_column}"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_asset_assettag', 'asset_assettag', ['asset_id', 'assettag_id'])
    op.create_unique_constraint('uq_asset_company', 'asset_company', ['asset_id', 'company_id'])
    op.create_unique_constraint('uq_asset_platform', 'asset_platform', ['asset_id', 'platform_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_platform', 'asset_platform', type_='unique')
    op.drop_constraint('uq_asset_company', 'asset_company', type_='unique')
    op.drop_constraint('uq_asset_assettag', 'asset_assettag', type_='unique')
    # ### end Alembic commands ###
