"""Add more files associations to MagDb.

Revision ID: a97d1f1210d8
Revises: e73df6fef942
Create Date: 2022-10-23 16:03:11.909771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97d1f1210d8'
down_revision = 'e73df6fef942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('magazine_issue_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'files', 'magazine_issue_versions', ['magazine_issue_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'magazine_issue_version_id')
    # ### end Alembic commands ###
