"""AssetTag: add link_text

Revision ID: aab311acf6d9
Revises: be8c223df414
Create Date: 2024-07-29 19:26:45.876705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab311acf6d9'
down_revision = 'be8c223df414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('link_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'link_title')
    # ### end Alembic commands ###
