"""Magazine.slug

Revision ID: b943b482152b
Revises: bfcc5df6bedc
Create Date: 2026-02-07 11:25:54.829620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b943b482152b'
down_revision = 'bfcc5df6bedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'magazines', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'magazines', type_='unique')
    op.drop_column('magazines', 'slug')
    # ### end Alembic commands ###
