"""Separate PushKey out of EventSession

Revision ID: bbbc6f6693ae
Revises: c470126faa09
Create Date: 2025-11-29 22:27:48.384379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbbc6f6693ae'
down_revision = 'c470126faa09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create the new push_keys table
    op.create_table('push_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('uses_remaining', sa.Integer(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.Column('authorized_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authorized_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_keys_key'), 'push_keys', ['key'], unique=False)
    
    # 2. Add push_key_id column to event_sessions
    op.add_column('event_sessions', sa.Column('push_key_id', sa.Integer(), nullable=True))
    
    # 3. Migrate data: create push_keys from event_sessions that have push_key data
    connection = op.get_bind()
    
    # Get all event_sessions with push_key data
    event_sessions = connection.execute(
        sa.text("SELECT id, push_key, push_key_uses_remaining, authorized_at, authorized_by_user_id FROM event_sessions WHERE push_key IS NOT NULL")
    ).fetchall()
    
    for es in event_sessions:
        es_id, push_key, uses_remaining, authorized_at, authorized_by_user_id = es
        
        # Skip if missing required fields
        if authorized_at is None or authorized_by_user_id is None:
            continue
            
        # Insert into push_keys and get the id
        result = connection.execute(
            sa.text("INSERT INTO push_keys (key, uses_remaining, authorized_at, authorized_by_user_id) VALUES (:key, :uses_remaining, :authorized_at, :authorized_by_user_id) RETURNING id"),
            {"key": push_key, "uses_remaining": uses_remaining, "authorized_at": authorized_at, "authorized_by_user_id": authorized_by_user_id}
        )
        push_key_id = result.fetchone()[0]
        
        # Update event_session with push_key_id
        connection.execute(
            sa.text("UPDATE event_sessions SET push_key_id = :push_key_id WHERE id = :id"),
            {"push_key_id": push_key_id, "id": es_id}
        )
    
    # 4. Drop old columns and constraints
    op.drop_index(op.f('ix_event_sessions_push_key'), table_name='event_sessions')
    op.drop_constraint(op.f('event_push_keys_authorized_by_user_id_fkey'), 'event_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'event_sessions', 'push_keys', ['push_key_id'], ['id'])
    op.drop_column('event_sessions', 'push_key_uses_remaining')
    op.drop_column('event_sessions', 'authorized_by_user_id')
    op.drop_column('event_sessions', 'authorized_at')
    op.drop_column('event_sessions', 'push_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    raise NotImplementedError("Downgrade not supported for this migration.")
    # ### end Alembic commands ###
