"""Wikipedia URL columns on Magazine

Revision ID: bfcc5df6bedc
Revises: cf3fa3f4d1e9
Create Date: 2026-02-07 11:12:03.890831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcc5df6bedc'
down_revision = 'cf3fa3f4d1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('url_wikipedia_cs', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_wikipedia_en', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_wikidata', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'url_wikidata')
    op.drop_column('magazines', 'url_wikipedia_en')
    op.drop_column('magazines', 'url_wikipedia_cs')
    # ### end Alembic commands ###
