"""Add EventSession.created_at

Revision ID: c470126faa09
Revises: 0a73573cde8f
Create Date: 2025-11-29 22:10:02.897342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c470126faa09'
down_revision = '0a73573cde8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_sessions', 'created_at')
    # ### end Alembic commands ###
