"""Add unique index to MagazineIssue.issue_number+MagazineIssue.magazine_id.

Revision ID: c69659a392d3
Revises: 498e21bb2701
Create Date: 2023-11-21 19:06:28.193665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69659a392d3'
down_revision = '498e21bb2701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_unique_issue', 'magazine_issues', ['issue_number', 'magazine_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('_unique_issue', 'magazine_issues', type_='unique')
    # ### end Alembic commands ###
