"""URL columns on Magazine

Revision ID: cf3fa3f4d1e9
Revises: fe651a7ca514
Create Date: 2026-02-07 10:56:20.924454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3fa3f4d1e9'
down_revision = 'fe651a7ca514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('url_archive_org', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_ndk_cz', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_dikda_sk', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_level_archiv', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_arbitrary', sa.String(), nullable=True))
    op.add_column('magazines', sa.Column('url_arbitrary_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'url_arbitrary_title')
    op.drop_column('magazines', 'url_arbitrary')
    op.drop_column('magazines', 'url_level_archiv')
    op.drop_column('magazines', 'url_dikda_sk')
    op.drop_column('magazines', 'url_ndk_cz')
    op.drop_column('magazines', 'url_archive_org')
    # ### end Alembic commands ###
