"""FileCategory: add document

Revision ID: d66cd7fd0e37
Revises: 2cb264c96fce
Create Date: 2024-07-28 22:14:38.708835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66cd7fd0e37'
down_revision = '2cb264c96fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'filecategory', ['collection', 'cover_page', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'test_result', 'text', 'transcription', 'unknown'], ['collection', 'cover_page', 'document', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'test_result', 'text', 'transcription', 'unknown'], [('files', 'category')], False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'filecategory', ['collection', 'cover_page', 'document', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'test_result', 'text', 'transcription', 'unknown'], ['collection', 'cover_page', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'test_result', 'text', 'transcription', 'unknown'], [('files', 'category')], True)
    # ### end Alembic commands ###
