"""Add floppy disk capture reassignment fields

Revision ID: dcd2220e7afb
Revises: f67992ffdd05
Create Date: 2025-12-14 21:54:53.053818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd2220e7afb'
down_revision = 'f67992ffdd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
