"""Remove old event related tables

Revision ID: e16129c911ec
Revises: 52e6ee4f9e72
Create Date: 2025-11-15 20:15:56.542691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e16129c911ec'
down_revision = '52e6ee4f9e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarks')
    op.drop_table('event_checks')
    op.drop_table('events')
    op.drop_table('file_versions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('directory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modification_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modification_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modification_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('md5', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('sha256', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('exif_parsed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('exif', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('barcodes_decoded', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deletion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deletion_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('storage', postgresql.ENUM('local', 'local_nas', name='filestore'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deletion_user_id'], ['users.id'], name=op.f('file_versions_deletion_user_id_fkey')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('file_versions_file_id_fkey')),
    sa.ForeignKeyConstraint(['modification_user_id'], ['users.id'], name=op.f('file_versions_modification_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('file_versions_pkey'))
    )
    op.create_table('event_checks',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], name=op.f('event_checks_check_id_fkey')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_checks_event_id_fkey'))
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('unknown', 'expected', 'confirmed', 'in_progress', 'finished', 'paid', name='eventstatus'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_table('user_bookmarks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_bookmarked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('bookmarked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('user_bookmarks_asset_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_bookmarks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_bookmarks_pkey'))
    )
    # ### end Alembic commands ###
