"""Create TestAggregate

Revision ID: e2082a9824a2
Revises: 35012356b25e
Create Date: 2025-11-30 23:20:48.662429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2082a9824a2'
down_revision = '35012356b25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agg_test_aggregates',
    sa.Column('latest_test_event_data', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_event_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agg_test_aggregates')
    # ### end Alembic commands ###
