"""Add closed field to EventSession

Revision ID: e2b14e1a005e
Revises: 7d1915132760
Create Date: 2025-12-14 22:47:56.572623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b14e1a005e'
down_revision = '7d1915132760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('closed', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_sessions', 'closed')
    # ### end Alembic commands ###
