"""add_background_color_to_file

Revision ID: e4fda14b7cd7
Revises: 6fa15bc35f26
Create Date: 2026-02-08 12:35:21.753286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e4fda14b7cd7'
down_revision = '6fa15bc35f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    backgroundcolor = postgresql.ENUM('light', 'dark', 'gray', name='backgroundcolor')
    backgroundcolor.create(op.get_bind())
    op.add_column('files', sa.Column('background_color', backgroundcolor, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'background_color')
    # ### end Alembic commands ###
