"""Chagne isbn and add few entries.

Revision ID: e73df6fef942
Revises: a57843bea4c3
Create Date: 2022-10-23 12:25:24.168049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73df6fef942'
down_revision = 'a57843bea4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazine_issue_versions', sa.Column('issn_or_isbn', sa.String(length=25), nullable=True))
    op.add_column('magazine_issue_versions', sa.Column('register_number_mccr', sa.String(), nullable=True))
    op.drop_column('magazine_issue_versions', 'isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazine_issue_versions', sa.Column('isbn', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('magazine_issue_versions', 'register_number_mccr')
    op.drop_column('magazine_issue_versions', 'issn_or_isbn')
    # ### end Alembic commands ###
