"""Rename EventSession.key to push_key

Revision ID: e8e187bdb507
Revises: 439778c97582
Create Date: 2025-11-29 21:35:04.830977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e187bdb507'
down_revision = '439778c97582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_sessions', 'key', new_column_name='push_key')
    op.alter_column('event_sessions', 'uses_remaining', new_column_name='push_key_uses_remaining')
    op.drop_index(op.f('ix_event_sessions_key'), table_name='event_sessions')
    op.create_index(op.f('ix_event_sessions_push_key'), 'event_sessions', ['push_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError("Downgrade not supported for this migration.")
    # ### end Alembic commands ###
