"""Add last used column to Company

Revision ID: e937ede96e7d
Revises: d87f6963cc75
Create Date: 2022-10-29 12:23:57.091211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e937ede96e7d'
down_revision = 'd87f6963cc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_used', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'last_used')
    # ### end Alembic commands ###
