"""Add URL and peňouze ID to Transaction

Revision ID: ed5b345f047a
Revises: 7601c1d79d2d
Create Date: 2021-11-08 18:30:06.135967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5b345f047a'
down_revision = '7601c1d79d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('penouze_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'penouze_id')
    op.drop_column('transactions', 'url')
    # ### end Alembic commands ###
