"""Add expiration of dbevents

Revision ID: f41023979088
Revises: 10c4d1c36bb3
Create Date: 2025-11-18 21:33:39.578357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41023979088'
down_revision = '10c4d1c36bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_push_keys', sa.Column('uses_remaining', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_class_name'), 'events', ['class_name'], unique=False)
    op.create_index(op.f('ix_events_namespace'), 'events', ['namespace'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_namespace'), table_name='events')
    op.drop_index(op.f('ix_events_class_name'), table_name='events')
    op.drop_column('event_push_keys', 'uses_remaining')
    # ### end Alembic commands ###
