"""Add screenshot file category

Revision ID: f67992ffdd05
Revises: 7c2194c5fb95
Create Date: 2025-12-14 20:36:33.486650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67992ffdd05'
down_revision = '7c2194c5fb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'filecategory', ['collection', 'cover_page', 'document', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'test_result', 'text', 'transcription', 'unknown'], ['collection', 'cover_page', 'document', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'screenshot', 'test_result', 'text', 'transcription', 'unknown'], [('files', 'category')], False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'filecategory', ['collection', 'cover_page', 'document', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'screenshot', 'test_result', 'text', 'transcription', 'unknown'], ['collection', 'cover_page', 'document', 'dump', 'dump_metadata', 'image', 'index_page', 'logo', 'other', 'photo', 'prose', 'raw_scan', 'scan', 'test_result', 'text', 'transcription', 'unknown'], [('files', 'category')], True)
    # ### end Alembic commands ###
