"""Add blake3 hash to file

Revision ID: fe651a7ca514
Revises: 537c1de085d1
Create Date: 2025-12-18 18:07:04.916895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe651a7ca514'
down_revision = '537c1de085d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('blake3', sa.LargeBinary(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'blake3')
    # ### end Alembic commands ###
