-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-01-12 10:48:30 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE asset 
    (
     id INTEGER NOT NULL , 
     parent_id INTEGER , 
     name VARCHAR NOT NULL , 
     manufacturer VARCHAR , 
     model VARCHAR , 
     custom_code VARCHAR , 
     location_id INTEGER , 
     category_id INTEGER NOT NULL , 
     note TEXT , 
     serial VARCHAR , 
     condition INTEGER NOT NULL , 
     functionality INTEGER NOT NULL , 
     status INTEGER NOT NULL 
    )
GO

ALTER TABLE asset ADD CONSTRAINT Asset_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE asset_meta 
    (
     id INTEGER NOT NULL , 
     asset_id INTEGER NOT NULL , 
     "key" VARCHAR NOT NULL , 
     value TEXT 
    )
GO

ALTER TABLE asset_meta ADD CONSTRAINT asset_meta_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE category 
    (
     id INTEGER NOT NULL , 
     name VARCHAR NOT NULL , 
     prefix VARCHAR , 
     counter INTEGER 
    )
GO

ALTER TABLE category ADD CONSTRAINT category_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE category_template 
    (
     id INTEGER NOT NULL , 
     category_id INTEGER , 
     "key" VARCHAR NOT NULL , 
     value TEXT 
    )
GO

ALTER TABLE category_template ADD CONSTRAINT asset_template_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE "check" 
    (
     id INTEGER NOT NULL , 
     type INTEGER NOT NULL , 
     user_id INTEGER NOT NULL , 
     date_from DATETIME , 
     date_to DATETIME , 
     status INTEGER NOT NULL , 
     note TEXT 
    )
GO

ALTER TABLE "check" ADD CONSTRAINT check_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE check_item 
    (
     id BIGINT NOT NULL , 
     check_id INTEGER NOT NULL , 
     barcode VARCHAR NOT NULL , 
     original_barcode VARCHAR , 
     status INTEGER NOT NULL 
    )
GO

ALTER TABLE check_item ADD CONSTRAINT check_item_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE check_log 
    (
     id INTEGER NOT NULL , 
     check_id INTEGER , 
     asset_id INTEGER , 
     location_id INTEGER , 
     original_location_id INTEGER , 
     change INTEGER 
    )
GO

ALTER TABLE check_log ADD CONSTRAINT check_protocol_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE event 
    (
     id INTEGER NOT NULL , 
     name VARCHAR NOT NULL , 
     place VARCHAR , 
     date_from DATE , 
     date_to DATE , 
     status INTEGER NOT NULL , 
     requirements TEXT , 
     note TEXT 
    )
GO

ALTER TABLE event ADD CONSTRAINT event_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE event_check 
    (
     event_id INTEGER NOT NULL , 
     check_id INTEGER NOT NULL 
    )
GO

ALTER TABLE event_check ADD CONSTRAINT event_check__UN UNIQUE NONCLUSTERED (event_id, check_id)
GO

CREATE TABLE location 
    (
     id INTEGER NOT NULL , 
     parent_id INTEGER , 
     name VARCHAR NOT NULL , 
     note TEXT 
    )
GO

ALTER TABLE location ADD CONSTRAINT location_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE "transaction" 
    (
     id INTEGER NOT NULL , 
     transaction_type INTEGER , 
     user_id INTEGER NOT NULL , 
     counterparty VARCHAR , 
     cost DECIMAL (28) , 
     note TEXT , 
     date DATETIME 
    )
GO

ALTER TABLE "transaction" ADD CONSTRAINT transaction_PK PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE transaction_asset 
    (
     asset_id INTEGER NOT NULL , 
     transaction_id INTEGER NOT NULL 
    )
GO

ALTER TABLE transaction_asset ADD CONSTRAINT transaction_asset__UN UNIQUE NONCLUSTERED (asset_id, transaction_id)
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
